name: Compress Images
on:
  push:
    branches: [master,image-optimization-quality-70]
    # Run Image Actions when JPG, JPEG, PNG or WebP files are added or changed.
    # See https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#onpushpull_requestpaths for reference.
    paths:
      - '**.*'
      - '**.jpg'
      - '**.jpeg'
      - '**.png'
      - '**.webp'
jobs:
  build:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.IMAGE_OPTIMIZATION_ACTION_TOKEN }}
          compressOnly: true
          jpegQuality: '70'
          jpegProgressive: false
          pngQuality: '70'
          webpQuality: '70'

      - name: Add image changes to file
        if: steps.calibre.outputs.markdown != ''
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          echo "${{ steps.calibre.outputs.markdown }}" > optimized-images-report.md
          git add -A
          git commit -m "Add Optimized images report"  
       
      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v3
        
        with:
          title: Compressed Images
          branch-suffix: timestamp
          commit-message: Compressed Images
          #body: ${{ steps.calibre.outputs.markdown }}
